### ISSUE TITLE
xpack out of the box?

### ISSUE THREAD

**Issue by chrono** [elastic/logstash-docker#15]
In https://github.com/elastic/logstash-docker/commit/71285d32c7c4232f9790045a89c3e9ecc6fcc163 some X-Pack support is added. 
https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash.yml#L2-L4

This causes error spam:

```[2017-02-26T23:04:38,679][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x55d22cea URL:http://logstash_system:xxxxxx@elasticsearch:9200/_xpack/monitoring/?system_id=logstash&system_api_version=2&interval=1s>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch"}```

And not the nice user experience that this block of code is supposed to give.
https://github.com/elastic/logstash-docker/blob/71285d32c7c4232f9790045a89c3e9ecc6fcc163/build/logstash/Dockerfile#L21-L22

**Comment by kevingimbel** [comment]
I am also seeing these logs show up. An option to turn this off would be nice IMO - also a way to configure the monitoring variables like URLs, username, password, and so on.  Maybe make the config use environment variables?

```yml
xpack.monitoring.elasticsearch.url: $ES_URL:$ES_PORT
xpack.monitoring.elasticsearch.username: $ES_USER
xpack.monitoring.elasticsearch.password: $ES_PW
```
And then run the container with
```sh
$ docker run --rm \
-e "ES_URL=https://my.elastic.url" \
-e "ES_PORT=0234" \
-e "ES_USER=logstash_user" \
-e "ES_PW=super_secret" \
docker.elastic.co/logstash/logstash:5.2.1
```

or from a `docker-compose` file:

```yml
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.1
    environment:
      ES_URL: "https://my.elastic.url"
```

And set the default values inside the Dockerfile.

```dockerfile
ENV ES_URL "http://elasticsearch:9200"
```
Might not be the best solution though, depending on how much else is configurable.

--- 

As it is I do not see a way to configure these variables unless I add my own `logstash.yml` file to `opt/logstash/conf` folder and it seems this cannot be blocked / turned off without adding a custom config file. Am I missing something?
