### ISSUE TITLE
Logstash.outputs.elasticsearch is trying to connect to another elasticsearch

### ISSUE THREAD

**Issue by a1exus** [elastic/logstash-docker#55]
I'm looking at [Settings File | Logstash Reference [5.6] | Elastic](https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html) and I'm unable to figure out, which setting to adjust to override _elasticsearch:9200_?

My docker:

```
root@app11:/opt/elastic/logstash# grep -v ^# docker-compose.yml 
version: '3'
services:
        logstash:
                image: docker.elastic.co/logstash/logstash:5.6.2
                container_name: logstash11
root@app11:/opt/elastic/logstash#
```

Please advise.

---

I created same topic at [Logstash.outputs.elasticsearch is trying to connect to another elasticsearch - Logstash - Discuss the Elastic Stack](https://discuss.elastic.co/t/logstash-outputs-elasticsearch-is-trying-to-connect-to-another-elasticsearch/101526)
