### ISSUE TITLE
shipped yaml config sets path.config disabling multiple pipelines and centralized management

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash-docker#64]
In both [oss](https://github.com/elastic/logstash-docker/blob/6.0/build/logstash/config/logstash-oss.yml#L2) and [xpack](https://github.com/elastic/logstash-docker/blob/6.0/build/logstash/config/logstash-x-pack.yml#L2) yaml configs the `path.config` is set.

In logstash, setting -f (--path.config) disables reading the pipelines.yml file and the centralized management, creating some confusions for users that try to enable these features when using this docker image.

I'm not sure if this is just a documentation gap, if we should change the defaults in the docker image, or change how logstash chooses between these modes of execution.

**Comment by endersonmaia** [comment]
And how can I enable it to read a `pipelines.yml` ?

**Comment by jarpy** [comment]
Thanks for the report, @jsvd. I am intimately familiar with this problem, having built a [workaround for it in the Puppet module](https://github.com/elastic/puppet-logstash/blob/4e0fc23ad2398dc324a0cf4bc8287f97acdb3783/spec/acceptance/class_logstash_spec.rb#L243,L245). The Debian and RPM packages for Logstash ship with a similar thing (they set `path.config` in the init scripts/units), which is why the Puppet module needs to do some trickery. I should have realised immediately that the same issue would apply here.

I actually [raised an issue](https://github.com/elastic/logstash/issues/8660) against you guys (the Logstash team), so it's only fair for you to raise one against me! :) I realise that you know all this already, but I want to make sure everyone is included in the conversation.

Until we make something nicer, @endersonmaia, you can set `path.config` to `null`. Here's an example in Compose:
``` yaml
version: '2'
services:
 logstash:
    image: docker.elastic.co/logstash/logstash:6.0.0
    environment:
      - path.config=null
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
```
